version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./themes:/var/www/html/themes:ro
    environment:
      - MYSQL_HOST=db
    env_file:
      - db.env
      - app.env
    depends_on:
      - db

  web:
    image: nginx:alpine
    restart: always
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - nextcloud:/var/www/html:ro
      - ./themes:/var/www/html/themes:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  db:
  nextcloud:
